---
- name: Install and start nginx
  hosts: all
  become: root

  tasks:
    - name: Install nginx
#      shell: apt install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx
#      shell: systemctl start nginx
      service:
        name: nginx
        state: started